version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/services/airex-api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/services/airex-worker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
