version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    FRONTEND_BUCKET: airex-prod-frontend
    CLOUDFRONT_DISTRIBUTION_ID: REPLACE_ME

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - npm ci --prefix apps/web
      - npm run build --prefix apps/web
  post_build:
    commands:
      - aws s3 sync apps/web/dist s3://$FRONTEND_BUCKET --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

cache:
  paths:
    - apps/web/node_modules/**/*
