version: 0.2

phases:
  install:
    commands:
      - python3 -m pip install --upgrade pip
      - |
          if [[ -f services/airex-api/requirements.txt ]]; then
            python3 -m pip install -r services/airex-api/requirements.txt
          else
            python3 -m pip install -r backend/requirements.txt
          fi
  build:
    commands:
      - cd database
      - alembic upgrade head
